# Stubs for tensorflow.python.framework.errors_impl (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.core.lib.core import error_codes_pb2 as error_codes_pb2
from tensorflow.python.framework import c_api_util as c_api_util
from tensorflow.python.util import compat as compat, deprecation as deprecation, tf_inspect as tf_inspect
from tensorflow.python.util.tf_export import tf_export as tf_export
from typing import Any as Any

class OpError(Exception):
    def __init__(self, node_def: Any, op: Any, message: Any, error_code: Any) -> None: ...
    def __reduce__(self): ...
    @property
    def message(self): ...
    @property
    def op(self): ...
    @property
    def error_code(self): ...
    @property
    def node_def(self): ...

OK: Any
CANCELLED: Any
UNKNOWN: Any
INVALID_ARGUMENT: Any
DEADLINE_EXCEEDED: Any
NOT_FOUND: Any
ALREADY_EXISTS: Any
PERMISSION_DENIED: Any
UNAUTHENTICATED: Any
RESOURCE_EXHAUSTED: Any
FAILED_PRECONDITION: Any
ABORTED: Any
OUT_OF_RANGE: Any
UNIMPLEMENTED: Any
INTERNAL: Any
UNAVAILABLE: Any
DATA_LOSS: Any

class CancelledError(OpError):
    def __init__(self, node_def: Any, op: Any, message: Any) -> None: ...

class UnknownError(OpError):
    def __init__(self, node_def: Any, op: Any, message: Any, error_code: Any = ...) -> None: ...

class InvalidArgumentError(OpError):
    def __init__(self, node_def: Any, op: Any, message: Any) -> None: ...

class DeadlineExceededError(OpError):
    def __init__(self, node_def: Any, op: Any, message: Any) -> None: ...

class NotFoundError(OpError):
    def __init__(self, node_def: Any, op: Any, message: Any) -> None: ...

class AlreadyExistsError(OpError):
    def __init__(self, node_def: Any, op: Any, message: Any) -> None: ...

class PermissionDeniedError(OpError):
    def __init__(self, node_def: Any, op: Any, message: Any) -> None: ...

class UnauthenticatedError(OpError):
    def __init__(self, node_def: Any, op: Any, message: Any) -> None: ...

class ResourceExhaustedError(OpError):
    def __init__(self, node_def: Any, op: Any, message: Any) -> None: ...

class FailedPreconditionError(OpError):
    def __init__(self, node_def: Any, op: Any, message: Any) -> None: ...

class AbortedError(OpError):
    def __init__(self, node_def: Any, op: Any, message: Any) -> None: ...

class OutOfRangeError(OpError):
    def __init__(self, node_def: Any, op: Any, message: Any) -> None: ...

class UnimplementedError(OpError):
    def __init__(self, node_def: Any, op: Any, message: Any) -> None: ...

class InternalError(OpError):
    def __init__(self, node_def: Any, op: Any, message: Any) -> None: ...

class UnavailableError(OpError):
    def __init__(self, node_def: Any, op: Any, message: Any) -> None: ...

class DataLossError(OpError):
    def __init__(self, node_def: Any, op: Any, message: Any) -> None: ...

def exception_type_from_error_code(error_code: Any): ...
def error_code_from_exception_type(cls): ...

class raise_exception_on_not_ok_status:
    status: Any = ...
    def __enter__(self): ...
    def __exit__(self, type_arg: Any, value_arg: Any, traceback_arg: Any): ...
